name: gbk2utf8
description: A flutter package to convert gbk to utf-8.
version: 1.0.2
author: JZoom <jzoom811207@gmail.com>
homepage: https://github.com/lc-os/gbk2utf8

environment:
  sdk: ">=2.12.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
